### ISSUE TITLE
the inner function never runs 

### ISSUE THREAD

**Issue by Dujota** [dfloresca/FunWithFood#1]
https://github.com/dfloresca/FunWithFood/blob/4617f1d1c5c5d92a6428d46b5872bcd972c6de9d/controllers/recipe.js#L17

the inner functiuon asyn fin one user is probably what you want to have as the handler  vs the outer function that doesnt do anything except render a template of `return res.render("recipe/add");`

**Comment by dfloresca** [comment]
unnecessary function removed; replaced with isLoggedIn
