### ISSUE TITLE
Sequelize init and config seems a bit complicated 

### ISSUE THREAD

**Issue by Dujota** [dfloresca/FunWithFood#10]
you want the index of models to be a database.js in your config since its intrisicly tied to the initializion of your application. 

The database connection just has to be established and sequelize initialzied, from there, you just make straight queries to the db tables, you dont necissarily have to loop through each model file in the folder of models and preload them into the lib's memory. Seems like an overcomplication that is not required. 

reference: https://sequelize.org/docs/v6/getting-started/

**Comment by Dujota** [comment]
adversly the model setup is also a bit strange, you have to receive sqlize as the argument (due to the config setup) and then intialize the class within the HOC body. Its hard to read and follow. 

the beuaty of sequelize is in its simplicity of implementation. 

You can go the Functional way  https://sequelize.org/docs/v6/core-concepts/model-basics/#using-sequelizedefine

or 

the Classical way

https://sequelize.org/docs/v6/core-concepts/model-basics/#extending-model

**Comment by Dujota** [comment]
im not suggesting a re-write, just bringing this to your attention :)

**Comment by dfloresca** [comment]
acknowledged
