### ISSUE TITLE
ad cb(null) 

### ISSUE THREAD

**Issue by Dujota** [dfloresca/FunWithFood#13]
https://github.com/dfloresca/FunWithFood/blob/4617f1d1c5c5d92a6428d46b5872bcd972c6de9d/config/ppConfig.js#L40C6-L41C25

add the cb(null) in the catch block, so that passport knows that when it tried to find a user, it couldnt, so treat this req as a not signed in request

**Comment by dfloresca** [comment]
added cb(null)
