### ISSUE TITLE
/add doesnt make sense here based on the routing

### ISSUE THREAD

**Issue by Dujota** [dfloresca/FunWithFood#2]
https://github.com/dfloresca/FunWithFood/blob/4617f1d1c5c5d92a6428d46b5872bcd972c6de9d/controllers/recipe.js#L31

rendering a template of add recipe, doesnt make sense here considering its the show action for a given user

`return res.render("recipe/add");`.

**Comment by dfloresca** [comment]
fixed RESTFul routing
