### ISSUE TITLE
why not use receipe id instead of name 

### ISSUE THREAD

**Issue by Dujota** [dfloresca/FunWithFood#5]
https://github.com/dfloresca/FunWithFood/blob/4617f1d1c5c5d92a6428d46b5872bcd972c6de9d/controllers/recipe.js#L75

be carefull when doing these type of queries off a string value, id is always preferred. The reason being is that you are trying to find one where condition === true 

inherently where clauses return lists of values since a clause could be true for 1 or more items, all findOne does is gets the 1st item in the list of items that match your where clause

if doing off a string like name or somehting similar, always make sure that the value is normalized (all caps or all lowercase) and make sure you have database and model level unqiue validations

**Comment by dfloresca** [comment]
updated to search by id instead of name
