### ISSUE TITLE
be consistent

### ISSUE THREAD

**Issue by Dujota** [dfloresca/FunWithFood#6]
https://github.com/dfloresca/FunWithFood/blob/4617f1d1c5c5d92a6428d46b5872bcd972c6de9d/controllers/recipe.js#L98

in prev code above you were doing this 

`const value = req.params.value`

vs

`const {value} = req.params`

both work fine, always prefer destructuring where possible, but just be consistent in the methodology you write code in.

**Comment by dfloresca** [comment]
updated to fix consistency
