### ISSUE TITLE
i would extract the api calls to external services into a different file 

### ISSUE THREAD

**Issue by Dujota** [dfloresca/FunWithFood#7]
https://github.com/dfloresca/FunWithFood/blob/4617f1d1c5c5d92a6428d46b5872bcd972c6de9d/controllers/recipe.js#L108

although this works fine, its always best to create a module (separate file) where you have all your 3rd party api calls encapsulated inside functions thaty you can import and use in different places.

this helps keep your code modular and DRY. 

something liek 
```
// utils or lib/services/apiName.js
function async parseRecipie(val1, val2 etc.. ){
const result = await  ... your api call from controller 
 
 return result
}

module.exports {
 parseRecipie,
}
```

**Comment by dfloresca** [comment]
successfully extracted API to separate file
